name: groupthree_chatapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core v3 Series
  firebase_core: ^3.1.1

  # Firebase v5 Series (Compatible with firebase_core v3)
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.3

  # Other dependencies
  provider: ^6.1.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/